# -*- coding: utf-8 -*-
"""raster data analysis.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/15Qs0qT0xD1B5XAEnpGOC8gT0lRjaFW1i
"""

import rasterio
rasterio.__version__

in_img = r'/nepal_lc_2020.tif'
ds = rasterio.open(in_img)
ds

data = ds.read()

data

ds.meta

ds.name

ds.count

ds.shape

ds.width

ds.height

ds.driver

ds.crs

ds.transform

ds.descriptions

data.size

data.dtype

data.min()

data.max()

from rasterio.plot import show
show(ds, cmap="winter", title='Land cover Map of Nepal')

from rasterio.plot import show, show_hist
show_hist(ds,bins=50 , title='Land cover Map of Nepal')

with rasterio.open(r"/var/output/nepal_lc_2023_out.tif", 'w',
                   driver = ds.driver,
                   height = ds.height,
                   width = ds.width,
                   count = ds.count,
                   crs = ds.crs,
                   transform = ds.transform,
                   dtype = data.dtype,
                   ) as dst:
                   dst.write(data)

ds_out = rasterio.open('/var/output/nepal_lc_2023_out.tif')
show(ds_out)